logging:
  level:
    org:
      springframework: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/cstore
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      schema-locations:
        classpath:schema.sql
      data-locations:
        classpath:data.sql
